/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Calculadora;

import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author EDUARDO.C
 */
public class VentanaDivisas extends javax.swing.JFrame {

    public String monto = "0";
    public boolean punto = true;
    public double dinero, cambio;

    public VentanaDivisas() {
        initComponents();
        this.setSize(380, 570);
        setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jButton11 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jvalor1 = new javax.swing.JLabel();
        Lista1 = new javax.swing.JComboBox<>();
        jvalor2 = new javax.swing.JLabel();
        lista2 = new javax.swing.JComboBox<>();
        botonreset = new javax.swing.JButton();
        botonborrar = new javax.swing.JButton();
        botonsiete = new javax.swing.JButton();
        botonocho = new javax.swing.JButton();
        botonnueve = new javax.swing.JButton();
        botoncuatro = new javax.swing.JButton();
        botoncinco = new javax.swing.JButton();
        botonseis = new javax.swing.JButton();
        botonuno = new javax.swing.JButton();
        botondos = new javax.swing.JButton();
        botontres = new javax.swing.JButton();
        botoncero = new javax.swing.JButton();
        botonpunto = new javax.swing.JButton();
        cifra1 = new javax.swing.JLabel();
        cifra2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        Menu = new javax.swing.JMenu();
        Caluladora = new javax.swing.JMenuItem();
        Salida = new javax.swing.JMenuItem();

        jButton11.setText("jButton11");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(380, 530));
        setPreferredSize(new java.awt.Dimension(0, 0));
        setSize(new java.awt.Dimension(380, 560));

        jPanel1.setMinimumSize(new java.awt.Dimension(380, 530));
        jPanel1.setPreferredSize(new java.awt.Dimension(380, 530));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jvalor1.setFont(new java.awt.Font("Arial Black", 0, 30)); // NOI18N
        jvalor1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jvalor1.setText("$");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 0, 15);
        jPanel1.add(jvalor1, gridBagConstraints);

        Lista1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dolar-estado unidense", "Peso-chileno", "Real-brasileño", "Euro-europa" }));
        Lista1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Lista1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 0, 15);
        jPanel1.add(Lista1, gridBagConstraints);

        jvalor2.setFont(new java.awt.Font("Arial Black", 0, 30)); // NOI18N
        jvalor2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jvalor2.setText("$");
        jvalor2.setPreferredSize(new java.awt.Dimension(20, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(10, 15, 0, 15);
        jPanel1.add(jvalor2, gridBagConstraints);

        lista2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dolar-estado unidense", "Peso-chileno", "Real-brasileño", "Euro-europa", " " }));
        lista2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lista2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 5, 15);
        jPanel1.add(lista2, gridBagConstraints);

        botonreset.setText("c");
        botonreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonresetActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 40;
        gridBagConstraints.ipady = 40;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        jPanel1.add(botonreset, gridBagConstraints);

        botonborrar.setText("x");
        botonborrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonborrarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 40;
        gridBagConstraints.ipady = 40;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
        jPanel1.add(botonborrar, gridBagConstraints);

        botonsiete.setText("7");
        botonsiete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonsieteActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 40;
        gridBagConstraints.ipady = 40;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 0);
        jPanel1.add(botonsiete, gridBagConstraints);

        botonocho.setText("8");
        botonocho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonochoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 40;
        gridBagConstraints.ipady = 40;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        jPanel1.add(botonocho, gridBagConstraints);

        botonnueve.setText("9");
        botonnueve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonnueveActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 40;
        gridBagConstraints.ipady = 40;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
        jPanel1.add(botonnueve, gridBagConstraints);

        botoncuatro.setText("4");
        botoncuatro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botoncuatroActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 40;
        gridBagConstraints.ipady = 40;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 0);
        jPanel1.add(botoncuatro, gridBagConstraints);

        botoncinco.setText("5");
        botoncinco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botoncincoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 40;
        gridBagConstraints.ipady = 40;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        jPanel1.add(botoncinco, gridBagConstraints);

        botonseis.setText("6");
        botonseis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonseisActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 40;
        gridBagConstraints.ipady = 40;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
        jPanel1.add(botonseis, gridBagConstraints);

        botonuno.setText("1");
        botonuno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonunoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 40;
        gridBagConstraints.ipady = 40;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 0);
        jPanel1.add(botonuno, gridBagConstraints);

        botondos.setText("2");
        botondos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botondosActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 40;
        gridBagConstraints.ipady = 40;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        jPanel1.add(botondos, gridBagConstraints);

        botontres.setText("3");
        botontres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botontresActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 40;
        gridBagConstraints.ipady = 40;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
        jPanel1.add(botontres, gridBagConstraints);

        botoncero.setText("0");
        botoncero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonceroActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 40;
        gridBagConstraints.ipady = 40;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        jPanel1.add(botoncero, gridBagConstraints);

        botonpunto.setText(".");
        botonpunto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonpuntoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 40;
        gridBagConstraints.ipady = 40;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
        jPanel1.add(botonpunto, gridBagConstraints);

        cifra1.setFont(new java.awt.Font("Arial Black", 0, 36)); // NOI18N
        cifra1.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 15);
        jPanel1.add(cifra1, gridBagConstraints);

        cifra2.setFont(new java.awt.Font("Arial Black", 0, 36)); // NOI18N
        cifra2.setText("0");
        cifra2.setPreferredSize(new java.awt.Dimension(20, 52));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(15, 0, 5, 15);
        jPanel1.add(cifra2, gridBagConstraints);

        Menu.setText("Menu");

        Caluladora.setText("Conversor calculadora");
        Caluladora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CaluladoraActionPerformed(evt);
            }
        });
        Menu.add(Caluladora);

        Salida.setText("Salir");
        Salida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalidaActionPerformed(evt);
            }
        });
        Menu.add(Salida);

        jMenuBar1.add(Menu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CaluladoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CaluladoraActionPerformed
        VentanaCalculadora calculadora = new VentanaCalculadora();
        calculadora.setVisible(true);
        dispose();
    }//GEN-LAST:event_CaluladoraActionPerformed

    private void botonunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonunoActionPerformed
        if (cifra1.getText() == "0") {
            monto = "1";
        } else {
            monto += "1";
        }

        cifra1.setText(monto);
        Obtenerdinero();
    }//GEN-LAST:event_botonunoActionPerformed

    private void botondosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botondosActionPerformed
        if (cifra1.getText() == "0") {
            monto = "2";
        } else {
            monto += "2";
        }
        cifra1.setText(monto);
        Obtenerdinero();
    }//GEN-LAST:event_botondosActionPerformed

    private void botontresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botontresActionPerformed
        if (cifra1.getText() == "0") {
            monto = "3";
        } else {
            monto += "3";
        }
        cifra1.setText(monto);
        Obtenerdinero();
    }//GEN-LAST:event_botontresActionPerformed

    private void botoncuatroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botoncuatroActionPerformed
        if (cifra1.getText() == "0") {
            monto = "4";
        } else {
            monto += "4";
        }
        cifra1.setText(monto);
        Obtenerdinero();
    }//GEN-LAST:event_botoncuatroActionPerformed

    private void botoncincoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botoncincoActionPerformed
        if (cifra1.getText() == "0") {
            monto = "5";
        } else {
            monto += "5";
        }
        cifra1.setText(monto);
        Obtenerdinero();
    }//GEN-LAST:event_botoncincoActionPerformed

    private void botonseisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonseisActionPerformed
        if (cifra1.getText() == "0") {
            monto = "6";
        } else {
            monto += "6";
        }
        cifra1.setText(monto);
        Obtenerdinero();
    }//GEN-LAST:event_botonseisActionPerformed

    private void botonsieteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonsieteActionPerformed
        if (cifra1.getText() == "0") {
            monto = "7";
        } else {
            monto += "7";
        }
        cifra1.setText(monto);
        Obtenerdinero();
    }//GEN-LAST:event_botonsieteActionPerformed

    private void botonochoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonochoActionPerformed
        if (cifra1.getText() == "0") {
            monto = "8";
        } else {
            monto += "8";
        }
        cifra1.setText(monto);
        Obtenerdinero();
    }//GEN-LAST:event_botonochoActionPerformed

    private void botonnueveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonnueveActionPerformed
        if (cifra1.getText() == "0") {
            monto = "9";
        } else {
            monto += "9";
        }
        cifra1.setText(monto);
        Obtenerdinero();
    }//GEN-LAST:event_botonnueveActionPerformed

    private void botonceroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonceroActionPerformed
        if (monto != "") {
            if (monto.length() > 1) {
                monto += "0";
            }

        } else {
            monto = "0";
        }
        cifra1.setText(monto);
        Obtenerdinero();
    }//GEN-LAST:event_botonceroActionPerformed

    private void Obtenerdinero() {
        Cambiodivisas();
        dinero = Double.parseDouble(monto);

        dinero *= cambio;
        cifra2.setText(String.format("%.2f", dinero));
    }

    private void Cambiodivisas() {
        if (Lista1.getSelectedItem() == "Dolar-estado unidense" && lista2.getSelectedItem() == "Dolar-estado unidense") {
            cambio = 1;
        }
        if (Lista1.getSelectedItem() == "Dolar-estado unidense" && lista2.getSelectedItem() == "Real-brasileño") {
            cambio = 5.18;
        }
        if (Lista1.getSelectedItem() == "Dolar-estado unidense" && lista2.getSelectedItem() == "Peso-chileno") {
            cambio = 834.15;
        }
        if (Lista1.getSelectedItem() == "Dolar-estado unidense" && lista2.getSelectedItem() == "Euro-europa") {
            cambio = 0.94;
        }
        if (Lista1.getSelectedItem() == "Real-brasileño" && lista2.getSelectedItem() == "Real-brasileño") {
            cambio = 1;
        }
        if (Lista1.getSelectedItem() == "Real-brasileño" && lista2.getSelectedItem() == "Dolar-estado unidense") {
            cambio = 0.19;
        }
        if (Lista1.getSelectedItem() == "Real-brasileño" && lista2.getSelectedItem() == "Peso-chileno") {
            cambio = 160.81;
        }
        if (Lista1.getSelectedItem() == "Real-brasileño" && lista2.getSelectedItem() == "Euro-europa") {
            cambio = 0.18;
        }
        if (Lista1.getSelectedItem() == "Euro-europa" && lista2.getSelectedItem() == "Real-brasileño") {
            cambio = 5.50;
        }
        if (Lista1.getSelectedItem() == "Euro-europa" && lista2.getSelectedItem() == "Peso-chileno") {
            cambio = 884.6;
        }
        if (Lista1.getSelectedItem() == "Euro-europa" && lista2.getSelectedItem() == "Euro-europa") {
            cambio = 1;
        }
        if (Lista1.getSelectedItem() == "Euro-europa" && lista2.getSelectedItem() == "Dolar-estado unidense") {
            cambio = 1.06;
        }
        if (Lista1.getSelectedItem() == "Peso-chileno" && lista2.getSelectedItem() == "Euro-europa") {
            cambio = 0.0011;
        }
        if (Lista1.getSelectedItem() == "Peso-chileno" && lista2.getSelectedItem() == "Dolar-estado unidense") {
            cambio = 0.0012;
        }
        if (Lista1.getSelectedItem() == "Peso-chileno" && lista2.getSelectedItem() == "Real-brasileño") {
            cambio = 0.0062;
        }
        if (Lista1.getSelectedItem() == "Peso-chileno" && lista2.getSelectedItem() == "Peso-chileno") {
            cambio = 1;
        }
    }

    private void Lista1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Lista1ActionPerformed

        if (Lista1.getSelectedItem() == "Dolar-estado unidense") {
            jvalor1.setText("$");
        } else if (Lista1.getSelectedItem() == "Real-brasileño") {
            jvalor1.setText("R$");
        } else if (Lista1.getSelectedItem() == "Euro-europa") {
            jvalor1.setText("€");
        } else if (Lista1.getSelectedItem() == "Peso-chileno") {
            jvalor1.setText("$");
        }
        Obtenerdinero();

    }//GEN-LAST:event_Lista1ActionPerformed

    private void lista2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lista2ActionPerformed

        if (lista2.getSelectedItem() == "Dolar-estado unidense") {
            jvalor2.setText("$");
        } else if (lista2.getSelectedItem() == "Real-brasileño") {
            jvalor2.setText("R$");
        } else if (lista2.getSelectedItem() == "Euro-europa") {
            jvalor2.setText("€");
        } else if (lista2.getSelectedItem() == "Peso-chileno") {
            jvalor2.setText("$");
        }
        Obtenerdinero();
    }//GEN-LAST:event_lista2ActionPerformed

    private void botonpuntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonpuntoActionPerformed
        if (punto == true) {
            if (monto != "") {
                monto += ".";
            } else {
                monto = "0.";
            }

        }
        cifra1.setText(monto);
        punto = false;
    }//GEN-LAST:event_botonpuntoActionPerformed

    private void botonresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonresetActionPerformed
        if (monto != "") {
            monto = "0";
            punto = true;
        }
        cifra1.setText(monto);
    }//GEN-LAST:event_botonresetActionPerformed

    private void botonborrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonborrarActionPerformed
        int i = 0;
        double tamaño =Double.parseDouble(monto);
        if (tamaño >0) {
            if (monto.length() == 1) {
                monto="0";
            }
            else{
                monto=monto.substring(0,monto.length()-1);
              
              cifra1.setText(monto);
               Obtenerdinero();
            }
           
            
        }

    }//GEN-LAST:event_botonborrarActionPerformed

    private void SalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalidaActionPerformed
        this.dispose();
    }//GEN-LAST:event_SalidaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaDivisas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaDivisas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaDivisas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaDivisas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaDivisas().setVisible(true);
            }
        });
        
          try {
        UIManager.setLookAndFeel("com.jtattoo.plaf.hifi.HiFiLookAndFeel");
    } catch (ClassNotFoundException ex) {
        //Logger.getLogger(Ventana.class.getName()).log(Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
       // Logger.getLogger(Ventana.class.getName()).log(Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
        //Logger.getLogger(Ventana.class.getName()).log(Level.SEVERE, null, ex);
    } catch (UnsupportedLookAndFeelException ex) {
       // Logger.getLogger(Ventana.class.getName()).log(Level.SEVERE, null, ex);
    }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Caluladora;
    private javax.swing.JComboBox<String> Lista1;
    private javax.swing.JMenu Menu;
    private javax.swing.JMenuItem Salida;
    private javax.swing.JButton botonborrar;
    private javax.swing.JButton botoncero;
    private javax.swing.JButton botoncinco;
    private javax.swing.JButton botoncuatro;
    private javax.swing.JButton botondos;
    private javax.swing.JButton botonnueve;
    private javax.swing.JButton botonocho;
    private javax.swing.JButton botonpunto;
    private javax.swing.JButton botonreset;
    private javax.swing.JButton botonseis;
    private javax.swing.JButton botonsiete;
    private javax.swing.JButton botontres;
    private javax.swing.JButton botonuno;
    private javax.swing.JLabel cifra1;
    private javax.swing.JLabel cifra2;
    private javax.swing.JButton jButton11;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jvalor1;
    private javax.swing.JLabel jvalor2;
    private javax.swing.JComboBox<String> lista2;
    // End of variables declaration//GEN-END:variables
}
