/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Calculadora;

import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author EDUARDO.C
 */
public class VentanaCalculadora extends javax.swing.JFrame {

   
    public char suma;
    public String cifra="";
    public String cifrasuma="";
    public double numero1;
    public boolean sumaactivo=false;
    public boolean activado=true;
    public  double resultado=0;
    public boolean restaactivo=false;
    public boolean multiplicaactivo=false;
    public boolean divisionactivo=false;
    public boolean punto=true;
    public boolean raizactivo=false;
    public VentanaCalculadora() {
        initComponents();
        this.setSize(380,530);
        campoOperaciones.setText("");
        setLocationRelativeTo(null);
       
        
    }
   public static String charToString(char ch) {
        return String.valueOf(ch);
    }
    public static String DoubleToString(double i) {
        return String.valueOf(i);
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        panel = new javax.swing.JPanel();
        campoOperaciones = new javax.swing.JLabel();
        etiquetaoperaciones = new javax.swing.JLabel();
        raizcuadrada = new javax.swing.JButton();
        botonborrar = new javax.swing.JButton();
        botondivision = new javax.swing.JButton();
        botonsiete = new javax.swing.JButton();
        botonreset = new javax.swing.JButton();
        botoncuatro = new javax.swing.JButton();
        botoncinco = new javax.swing.JButton();
        botonseis = new javax.swing.JButton();
        botonocho = new javax.swing.JButton();
        botonnueve = new javax.swing.JButton();
        botonmultiplicacion = new javax.swing.JButton();
        botonresta = new javax.swing.JButton();
        botonuno = new javax.swing.JButton();
        botondos = new javax.swing.JButton();
        botontres = new javax.swing.JButton();
        botonsuma = new javax.swing.JButton();
        boton = new javax.swing.JButton();
        botoncero = new javax.swing.JButton();
        botoncoma = new javax.swing.JButton();
        botonigual = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        Menu = new javax.swing.JMenu();
        conversordivisas = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        salir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(380, 530));

        panel.setPreferredSize(new java.awt.Dimension(380, 530));
        panel.setLayout(new java.awt.GridBagLayout());

        campoOperaciones.setFont(new java.awt.Font("Arial Black", 0, 36)); // NOI18N
        campoOperaciones.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        campoOperaciones.setText("0");
        campoOperaciones.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                campoOperacionesAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipady = 40;
        panel.add(campoOperaciones, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipady = 20;
        panel.add(etiquetaoperaciones, gridBagConstraints);

        raizcuadrada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/raiz1.png"))); // NOI18N
        raizcuadrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                raizcuadradaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.ipady = 50;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        panel.add(raizcuadrada, gridBagConstraints);

        botonborrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/backspace2.png"))); // NOI18N
        botonborrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonborrarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.ipady = 50;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        panel.add(botonborrar, gridBagConstraints);

        botondivision.setText("/");
        botondivision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botondivisionActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.ipady = 50;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        panel.add(botondivision, gridBagConstraints);

        botonsiete.setText("7");
        botonsiete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonsieteActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.ipady = 50;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        panel.add(botonsiete, gridBagConstraints);

        botonreset.setText("c");
        botonreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonresetActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.ipady = 50;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        panel.add(botonreset, gridBagConstraints);

        botoncuatro.setText("4");
        botoncuatro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botoncuatroActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.ipady = 50;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        panel.add(botoncuatro, gridBagConstraints);

        botoncinco.setText("5");
        botoncinco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botoncincoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.ipady = 50;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        panel.add(botoncinco, gridBagConstraints);

        botonseis.setText("6");
        botonseis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonseisActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.ipady = 50;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        panel.add(botonseis, gridBagConstraints);

        botonocho.setText("8");
        botonocho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonochoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.ipady = 50;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        panel.add(botonocho, gridBagConstraints);

        botonnueve.setText("9");
        botonnueve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonnueveActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.ipady = 50;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        panel.add(botonnueve, gridBagConstraints);

        botonmultiplicacion.setText("x");
        botonmultiplicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonmultiplicacionActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.ipady = 50;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        panel.add(botonmultiplicacion, gridBagConstraints);

        botonresta.setText("-");
        botonresta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonrestaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.ipady = 50;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        panel.add(botonresta, gridBagConstraints);

        botonuno.setText("1");
        botonuno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonunoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.ipady = 50;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        panel.add(botonuno, gridBagConstraints);

        botondos.setText("2");
        botondos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botondosActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.ipady = 50;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        panel.add(botondos, gridBagConstraints);

        botontres.setText("3");
        botontres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botontresActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.ipady = 50;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        panel.add(botontres, gridBagConstraints);

        botonsuma.setText("+");
        botonsuma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonsumaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.ipady = 50;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        panel.add(botonsuma, gridBagConstraints);

        boton.setText("+\n-");
        boton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.ipady = 50;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        panel.add(boton, gridBagConstraints);

        botoncero.setText("0");
        botoncero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonceroActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.ipady = 50;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        panel.add(botoncero, gridBagConstraints);

        botoncoma.setText(".");
        botoncoma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botoncomaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.ipady = 50;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        panel.add(botoncoma, gridBagConstraints);

        botonigual.setText("=");
        botonigual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonigualActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.ipady = 50;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        panel.add(botonigual, gridBagConstraints);

        Menu.setText("Menu");

        conversordivisas.setText("Conversor divisas");
        conversordivisas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conversordivisasActionPerformed(evt);
            }
        });
        Menu.add(conversordivisas);

        jMenuItem2.setText("Calculadora estandar");
        Menu.add(jMenuItem2);

        salir.setText("Salir");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });
        Menu.add(salir);

        jMenuBar1.add(Menu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, 405, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(51, Short.MAX_VALUE)
                .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void raizcuadradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_raizcuadradaActionPerformed
        if(activado==true){
          numero1=Double.parseDouble(cifra);
        etiquetaoperaciones.setText("sqrt("+cifra+")");
        resultado=Math.sqrt(numero1);
        
        cifra=String.valueOf(resultado);
       campoOperaciones.setText(cifra);
      
       //raizactivo=false;
       activado=false;
       }
    }//GEN-LAST:event_raizcuadradaActionPerformed

    private void botonunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonunoActionPerformed
      if(campoOperaciones.getText()=="0"){
          cifra="1";
      }else{
          cifra +="1";
      }
        
        
        campoOperaciones.setText(cifra);
        activado=true;
       
    }//GEN-LAST:event_botonunoActionPerformed

    private void botonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonActionPerformed
       if(cifra.charAt(0)!='-'){
           cifra="-"+cifra;
       }else{
           cifra=cifra.substring(1, cifra.length());
       }
       campoOperaciones.setText(cifra);
    }//GEN-LAST:event_botonActionPerformed

    private void botonochoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonochoActionPerformed
    if(campoOperaciones.getText()=="0"){
          cifra="8";
      }else{
          cifra +="8";
      }
        
        campoOperaciones.setText(cifra);
         activado=true;
    }//GEN-LAST:event_botonochoActionPerformed

    private void botonborrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonborrarActionPerformed
       
       if(cifra.length()>0){
           if(cifra.length()==1){
               cifra="0";
              
           
           }else{
                cifra=cifra.substring( 0,cifra.length()-1);
           }
           campoOperaciones.setText(cifra); 
       }

       
           activado=false;
    }//GEN-LAST:event_botonborrarActionPerformed

    private void botondosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botondosActionPerformed
       if(campoOperaciones.getText()=="0"){
          cifra="2";
      }else{
          cifra +="2";
      }
        
        campoOperaciones.setText(cifra);
         activado=true;
    }//GEN-LAST:event_botondosActionPerformed

    private void botonsumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonsumaActionPerformed
      // String num=campoOperaciones.getText();
       // int num1=Integer.parseInt(uno);
       sumaactivo=true;
         if(activado==true){
          numero1=Double.parseDouble(cifra);
        etiquetaoperaciones.setText(cifra+"+");
       cifra="";
      
       sumaactivo=true;   
       activado=false;
         }
      
          
    }//GEN-LAST:event_botonsumaActionPerformed

    private void botontresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botontresActionPerformed
          if(campoOperaciones.getText()=="0"){
          cifra="3";
      }else{
          cifra +="3";
      }
        
        campoOperaciones.setText(cifra);
         activado=true;
    }//GEN-LAST:event_botontresActionPerformed

    private void botoncuatroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botoncuatroActionPerformed
          if(campoOperaciones.getText()=="0"){
          cifra="4";
      }else{
          cifra +="4";
      }
        
        campoOperaciones.setText(cifra);
         activado=true;
    }//GEN-LAST:event_botoncuatroActionPerformed

    private void botoncincoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botoncincoActionPerformed
          if(campoOperaciones.getText()=="0"){
          cifra="5";
      }else{
          cifra +="5";
      }
        
        campoOperaciones.setText(cifra);
         activado=true;
    }//GEN-LAST:event_botoncincoActionPerformed

    private void botonseisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonseisActionPerformed
         if(campoOperaciones.getText()=="0"){
          cifra="6";
      }else{
          cifra +="6";
      }
        
        campoOperaciones.setText(cifra);
         activado=true;
    }//GEN-LAST:event_botonseisActionPerformed

    private void botonsieteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonsieteActionPerformed
          if(campoOperaciones.getText()=="0"){
          cifra="7";
      }else{
          cifra +="7";
      }
        
        campoOperaciones.setText(cifra);
         activado=true;
    }//GEN-LAST:event_botonsieteActionPerformed

    private void botonnueveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonnueveActionPerformed
      if(campoOperaciones.getText()=="0"){
          cifra="9";
      }else{
          cifra +="9";
      }
        
        campoOperaciones.setText(cifra);
         activado=true;
        
    }//GEN-LAST:event_botonnueveActionPerformed

    private void botonigualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonigualActionPerformed
      
      
        
        if(sumaactivo==false){
            campoOperaciones.setText(cifra);
        }
        else if(sumaactivo==true){
            double numero2=Double.parseDouble(cifra);
            resultado=numero1+numero2;
            
            campoOperaciones.setText(String.format("%.2f",resultado));
            cifra=String.valueOf(resultado);
            sumaactivo=false;
        }
       etiquetaoperaciones.setText("");
        activado=true;
   
        if(restaactivo==false){
            campoOperaciones.setText(cifra);
        }
        else if(restaactivo==true){
            double numero2=Double.parseDouble(cifra);
            resultado=numero1-numero2;
            
            campoOperaciones.setText(String.format("%.2f",resultado));
            cifra=String.valueOf(resultado);
            restaactivo=false;
        }
       etiquetaoperaciones.setText("");
       activado=true;
       
       
       if(multiplicaactivo==false){
            campoOperaciones.setText(cifra);
        }
        else if(multiplicaactivo==true){
            double numero2=Double.parseDouble(cifra);
            resultado=numero1*numero2;
            
            campoOperaciones.setText(String.format("%.2f",resultado));
            cifra=String.valueOf(resultado);
            multiplicaactivo=false;
        }
       etiquetaoperaciones.setText("");
       activado=true;
       
       
       if(divisionactivo==false){
            campoOperaciones.setText(cifra);
        }
        else if(divisionactivo==true){
            double numero2=Double.parseDouble(cifra);
            resultado=numero1/numero2;
            
            campoOperaciones.setText(String.format("%.2f",resultado));
            cifra=String.valueOf(resultado);
            divisionactivo=false;
        }
       
       
       etiquetaoperaciones.setText("");
       activado=true;
    }//GEN-LAST:event_botonigualActionPerformed

    private void conversordivisasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conversordivisasActionPerformed
        VentanaDivisas divisa=new VentanaDivisas();
        divisa.setVisible(true);
        dispose();
    }//GEN-LAST:event_conversordivisasActionPerformed

    private void campoOperacionesAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_campoOperacionesAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_campoOperacionesAncestorAdded

    private void botonrestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonrestaActionPerformed
       if(activado==true){
          numero1=Double.parseDouble(cifra);
        etiquetaoperaciones.setText(cifra+"-");
       cifra="";
      
       restaactivo=true;
       activado=false;
       }
    }//GEN-LAST:event_botonrestaActionPerformed

    private void botonmultiplicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonmultiplicacionActionPerformed
       if(activado=true){
           numero1=Double.parseDouble(cifra);
           etiquetaoperaciones.setText(cifra+ "*");
           cifra="";
           multiplicaactivo=true;
           activado=false;
       }
    }//GEN-LAST:event_botonmultiplicacionActionPerformed

    private void botondivisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botondivisionActionPerformed
        if(activado=true){
            numero1=Double.parseDouble(cifra);
            etiquetaoperaciones.setText(cifra+"/");
            cifra="";
            divisionactivo=true;
            activado=false;
        }
    }//GEN-LAST:event_botondivisionActionPerformed

    private void botonresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonresetActionPerformed
    
        campoOperaciones.setText("0");
        etiquetaoperaciones.setText("");
           cifra="";
       activado=true;
       
    }//GEN-LAST:event_botonresetActionPerformed

    private void botonceroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonceroActionPerformed
        if(cifra!=""){
            cifra+="0";
        }
        
        campoOperaciones.setText(cifra);
        activado=true;
    }//GEN-LAST:event_botonceroActionPerformed

    private void botoncomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botoncomaActionPerformed
       
        if (punto==true){
              if (cifra==""){
            cifra="0.";
            }
            else {
            cifra+=".";
                } 
              campoOperaciones.setText(cifra);
            punto=false;  
        }
     
    }//GEN-LAST:event_botoncomaActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
       
    }//GEN-LAST:event_salirActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws UnsupportedLookAndFeelException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaCalculadora().setVisible(true);
            }
        });
        
         try {
        UIManager.setLookAndFeel("com.jtattoo.plaf.hifi.HiFiLookAndFeel");
    } catch (ClassNotFoundException ex) {
        //Logger.getLogger(Ventana.class.getName()).log(Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
       // Logger.getLogger(Ventana.class.getName()).log(Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
        //Logger.getLogger(Ventana.class.getName()).log(Level.SEVERE, null, ex);
    } catch (UnsupportedLookAndFeelException ex) {
       // Logger.getLogger(Ventana.class.getName()).log(Level.SEVERE, null, ex);
    }
        /* Create and display the form */

        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Menu;
    private javax.swing.JButton boton;
    private javax.swing.JButton botonborrar;
    private javax.swing.JButton botoncero;
    private javax.swing.JButton botoncinco;
    private javax.swing.JButton botoncoma;
    private javax.swing.JButton botoncuatro;
    private javax.swing.JButton botondivision;
    private javax.swing.JButton botondos;
    private javax.swing.JButton botonigual;
    private javax.swing.JButton botonmultiplicacion;
    private javax.swing.JButton botonnueve;
    private javax.swing.JButton botonocho;
    private javax.swing.JButton botonreset;
    private javax.swing.JButton botonresta;
    private javax.swing.JButton botonseis;
    private javax.swing.JButton botonsiete;
    private javax.swing.JButton botonsuma;
    private javax.swing.JButton botontres;
    private javax.swing.JButton botonuno;
    private javax.swing.JLabel campoOperaciones;
    private javax.swing.JMenuItem conversordivisas;
    private javax.swing.JLabel etiquetaoperaciones;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel panel;
    private javax.swing.JButton raizcuadrada;
    private javax.swing.JMenuItem salir;
    // End of variables declaration//GEN-END:variables

 
}
